version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./trading_bot.db
      - BACKPACK_API_KEY=${BACKPACK_API_KEY:-your_api_key_here}
      - BACKPACK_SECRET_KEY=${BACKPACK_SECRET_KEY:-your_secret_key_here}
      - LOG_LEVEL=INFO
    volumes:
      - ./backend:/app
      - trading_data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  trading_data:
